server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      route:
#        id: business
#        uri: lb://business
#        predicates:
#          - Path=/business/**
#      discovery:
#        locator:
#          enabled: true

  service:
    jwt:
      secret-key: "36169d24b0c764b39af614c68c77e6f1aaaaf15c922bfc4152264418c703266e1061533461fb3b4e13b53873aa864e763859246bc67a4eb4f14c45b2582ec3d4"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/